# Generated by Django 5.2 on 2026-07-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
