# Generated by Django 5.2 on 2026-07-12 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('cargo_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planned_distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trip_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
        ),
    ]
