# Generated by Django 5.2 on 2026-07-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('maximum_load_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_odometer', models.PositiveIntegerField(default=0)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('insurance_expiry', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('In Shop', 'In Shop'), ('Retired', 'Retired')], default='Available', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
